# Generated by Django 2.2.5 on 2020-01-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartbins',
            old_name='threshold_value',
            new_name='garbage_value',
        ),
        migrations.AddField(
            model_name='smartbins',
            name='waste_type',
            field=models.CharField(choices=[('cardboard', 'Cardboard'), ('glass', 'Glass'), ('metal', 'Metal'), ('paper', 'Paper'), ('plastic', 'Plastic'), ('trash', 'Trash')], default='cardboard', max_length=10),
        ),
    ]
