# Generated by Django 2.2.5 on 2020-01-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0002_auto_20200131_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartbins',
            name='needs_to_be_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartbins',
            name='waste_collected',
            field=models.BooleanField(default=False),
        ),
    ]
