# Generated by Django 2.2.5 on 2020-01-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0003_auto_20200131_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartbins',
            name='bin_full',
            field=models.BooleanField(default=False),
        ),
    ]
