# Generated by Django 2.2.5 on 2020-01-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0004_smartbins_bin_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartbins',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='smartbins',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
