# Generated by Django 2.2.4 on 2020-01-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0005_auto_20200131_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalBins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
