# Generated by Django 2.2.4 on 2020-01-31 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0006_normalbins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normalbins',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='normalbins',
            old_name='longitude',
            new_name='lng',
        ),
    ]
