# Generated by Django 2.2.4 on 2020-02-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='col_lat',
            field=models.FloatField(default=12.654),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collector',
            name='col_lng',
            field=models.FloatField(default=75.6444),
            preserve_default=False,
        ),
    ]
